format = """
[](#540400)\
$os\
$username\
[](bg:#2D2D2D fg:#540400)\
$directory\
[](fg:#2D2D2D bg:#772200)\
$git_branch\
$git_status\
[](fg:#772200 bg:#1a1a1a)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#1a1a1a bg:#404040)\
$docker_context\
[](fg:#404040 bg:#550F00)\
$time\
[ ](fg:#550F00)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#540400"
style_root = "bg:#540400"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#540400"
disabled = true # Disabled by default

[directory]
style = "bg:#2D2D2D"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
symbol = " "
style = "bg:#1a1a1a"
format = '[ $symbol ($version) ]($style)'

[cpp]
symbol = " "
style = "bg:#1a1a1a"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#404040"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
style = "bg:#1a1a1a"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#1a1a1a"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#772200"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#772200"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#1a1a1a"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#1a1a1a"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#1a1a1a"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#1a1a1a"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#1a1a1a"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#1a1a1a"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:#1a1a1a"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#1a1a1a"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#1a1a1a"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#550F00"
format = '[  $time ]($style)'
